### ISSUE TITLE
Derive time/period codelists

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/pmd-jenkins-library#65]
Post process CSV/RDF outputs from dataset transforms to derive time/period codelists.

The hierarchy can be derived on the fly.

**Comment by rossbowen** [comment]
@robons just writing some thoughts.

Given the common `info.json` case:
```jsonc
// info.json
"Period": {
    "parent": "http://purl.org/linked-data/sdmx/2009/dimension#refPeriod",
    "value": "http://reference.data.gov.uk/id/{+period}"
}
```

The following RDF is generated relating a local dimension to a local codelist.
```ttl
<http://gss-data.org.uk/data/gss_data/trade/some-title#dimension/period>
  a <http://purl.org/linked-data/cube#DimensionProperty>;
  <http://www.w3.org/2000/01/rdf-schema#label> "Period"@en;
  <http://www.w3.org/2000/01/rdf-schema#range> <http://gss-data.org.uk/data/gss_data/trade/some-title#class/Period>;
  <http://purl.org/linked-data/cube#codeList> <http://gss-data.org.uk/data/gss_data/trade/some-title#scheme/period>;
  <http://www.w3.org/2000/01/rdf-schema#subPropertyOf> <http://purl.org/linked-data/sdmx/2009/dimension#refPeriod> .
```


Since this is to purely get filters/search to function in the short term, it would be ideal to populate these codelists with as little "baggage" as possible. 

This is a minimal example which populates the concept scheme with reference periods which feature in the dataset, though it misses any PMD specific metadata required to get the functionality. 
```rq
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
CONSTRUCT {       
    ?timeConcept skos:inScheme ?codelist.
}
WHERE {
    {
        SELECT DISTINCT ?codelist ?timeConcept ?conceptLabel
        WHERE {
            ?dimension a qb:DimensionProperty ;
                rdfs:subPropertyOf <http://purl.org/linked-data/sdmx/2009/dimension#refPeriod> ;
                qb:codeList ?codelist ;
                .
            ?observation ?dimension ?timeConcept.
        }
    }
}
```

If the codelist needs metadata itself such as a title, I don't think any control would be required from the DM in terms of giving this a name - some sensible placeholder such as always calling it "Reference Periods" would suffice for now and could form part of the `CONSTRUCT` query. Though if there is a counterexample where you feel more control _would_ be necessary then please do shout.

**Comment by robons** [comment]
@rossbowen What do we think about implementing this in the local build tool? We'd get a bunch of errors locally without it.

I suppose what I could so is pretent "codelist": false for all these timeperiods locally.

**Comment by robons** [comment]
I've done a thing. Now you should just need to ensure that your timeperiod has a parent of `sdmx:refPeriod` and that you don't say anything about the codelist used (i.e. `"codelist": false` has *not* been set in the info.json).
